bicicletas/config/routes.rb
Bicicletas::Application.routes.draw do
  get "page/home"
  get "page/about"
  devise_for :users
  

  resources :brands

  resources :bikes

   root 'page#home'

end

bicicletas/app/models/bike.rb
class Bike < ActiveRecord::Base
	belongs_to :brand
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar, :content_type => /.*\Z/
	
end

bicicletas/app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :bikes
	has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :logo, :content_type => /.*\Z/
	
end

bicicletas/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

bicicletas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bicicletas/app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :current_user, only: [:show, :edit, :update, :destroy]
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  # GET /bikes
  # GET /bikes.json
  def index
    if params[:id].nil?
      @bikes = Bike.paginate(:page => params[:page], :per_page => 2)
    else
      @bikes = Bike.where(:brand_id => params[:id])
      @bikes = @bikes.paginate(:page => params[:page], :per_page => 2)
  end
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
    #@brand = Brand.where(:id=Bike.find(params[:id]).brand_id)

  end

  # GET /bikes/new
  def new
    if !current_user.nil?
       @bike=Bike.new
      
    else
    render text: 'Usted tiene que registrarse para acceder a este campo'
    end 
  end

  # GET /bikes/1/edit
  def edit
  end

  # POST /bikes
  # POST /bikes.json
  def create
        if !current_user.nil?
  
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bike }
      else
        format.html { render action: 'new' }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
      end
     else
      render text: 'que te jodan melon'
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end
    #def set_brand
    #  @brand = Brand.find(@bike.brand_id)
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bike_params
      params.require(:bike).permit(:name, :description, :price, :avatar, :brand_id )
    end
    #def brand_params
     # params.require(:brand).permit(:id,:name)
    #end
end

bicicletas/app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.paginate(:page => params[:page], :per_page => 4)
  end
  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brand }
      else
        format.html { render action: 'new' }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:id, :name, :history, :localizacion, :logo)
    end
end

bicicletas/app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about
  end
end

bicicletas/app/helpers/application_helper.rb
module ApplicationHelper
end

bicicletas/app/helpers/bikes_helper.rb
module BikesHelper
end

bicicletas/app/helpers/brands_helper.rb
module BrandsHelper
end

bicicletas/app/helpers/page_helper.rb
module PageHelper
end

bicicletas/app/helpers/pages_helper.rb
module PagesHelper
end

bicicletas/app/views/bikes/_form.html.erb
<%= form_for(@bike) do |f| %>
  <% if @bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% @bike.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.file_field :avatar %>
  </div>
    <div class="field">
    <%= f.label :brand_id %><br>
    <%= f.number_field :brand_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bicicletas/app/views/bikes/edit.html.erb
<h1>Editing bike</h1>

<%= render 'form' %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

bicicletas/app/views/bikes/index.html.erb
  <tbody>
    <% @bikes.each do |bike| %>
    
      <div id="generar">

        <div id="contenido">
          <div id="image"><%= image_tag bike.avatar.url ,:width => 450 %></div>
          <div id="name"><%= bike.name %></div>
          <div id="description"><%= bike.description %></div>
          <div id="price">Precio: <%= bike.price %></div>
        </div>

        <div id="confirm">
          <%= link_to 'Show', bike %>
          <% if !current_user.nil? %>
          <%= link_to 'Edit', edit_bike_path(bike) %>
          <%= link_to 'Destroy', bike, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </div>
    <% end %>

  </tbody>

<br>
<% if !current_user.nil? %>
<%= link_to 'Go back',  brands_path %>
<% end %> 
<%= link_to 'New Bike', new_bike_path %>
<%= will_paginate @bikes %>

bicicletas/app/views/bikes/new.html.erb
<h1>New bike</h1>

<%= render 'form' %>

<%= link_to 'Back', bikes_path %>

bicicletas/app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @bike.avatar.url(:thumb) %>

<p>
  <strong>Name:</strong>
  <%= @bike.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bike.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bike.price %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @bike.brand.name %>
</p>

<% if !current_user.nil?%>
<%= link_to 'Edit', edit_bike_path(@bike) %> |
<% end %>
<%= link_to 'Back', bikes_path %>

bicicletas/app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :history %><br>
    <%= f.text_area :history %>
  </div>
  <div class="field">
    <%= f.label :localizacion %><br>
    <%= f.text_field :localizacion %>
  </div>
    <div class="field">
    <%= f.file_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bicicletas/app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

bicicletas/app/views/brands/index.html.erb
  <tbody id="marcas">
    <h3>Bienbenido a nuestro catalogo de marcas. </h1>
    <div id="general_brand">
    <% @brands.each do |brand| %>

      <div id="marcas_contenedor">
        <div id="contenedor">
            <div id="image"><%= link_to image_tag(brand.logo.url(:thumb)), :controller => "bikes" , :id => brand.id%></div>
        </div>

        <div id="confirm">
              <%= link_to '¿Que Marca es?', brand %>
            <% if !current_user.nil? %>
              <%= link_to 'Edit', edit_brand_path(brand) %>
              <%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </div>
      </div>
    <% end %> 
    </div>
  </tbody>



<br>
<% if !current_user.nil? %>
<%= link_to 'New Brand', new_brand_path %>
<%= will_paginate @bikes %>
<% end %>

bicicletas/app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

bicicletas/app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @brand.logo.url(:thumb) %>
<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>History:</strong>
  <%= @brand.history %>
</p>

<p>
  <strong>Localizacion:</strong>
  <%= @brand.localizacion %>
</p>
<!-- con esto metes los botones que no quieras que token dentro y te saldran solo cuando estas logueado-->
<% if !current_user.nil?%>
<%= link_to 'Edit', edit_brand_path(@brand) %> |
<% end %>
<%= link_to 'Back', brands_path %>

bicicletas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bicicletas</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= stylesheet_link_tag 'jquery.rambling.slider' %>
    <%= javascript_include_tag 'jquery.rambling.slider' %>
    <%= csrf_meta_tags %>


</head>
<body>
<div id="general">
  <div id="logo">
    <img src="http://logonoid.com/images/cannondale-logo.png"  height="50" width="42%">
  </div>

  <div id="user_nav">
    <% if user_signed_in? %>
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
  </div>

  <div id="head">
     <li><%= link_to 'Home', page_home_path%></li> 
     <li><%= link_to 'Brands', brands_path%></li> 
     <li><%= link_to 'About us', page_about_path%></li> 
  </div>
  <%= yield %>
</div>
</body>
</html>

bicicletas/app/views/page/about.html.erb
<header class="title">
    <h1 class="tgc">Company/Heritage</h1>
</header>

<section class="safetyBlock">
    <header class="leftHead">
        <h2 class="tgc">Heritage</h2>
    </header>

        <div class="safetyContent">
        <h3>
			Although we never forget our heritage, Cannondale and our dealers have come a long way since our birth in a crowded loft above a pickle factory in 1971.

        </h3>
        <br></br>
        <p>
			The company grew quickly during its early years. We introduced the cycling industry's first bicycle trailer, the Bugger, and added successful cycling apparel and accessory lines while earning a strong reputation for innovation and quality.

        </p>
        <p>
			That reputation proved invaluable when Cannondale introduced its first bicycle, a Touring model, in 1983. We raised the cycling world's eyebrows by building our bicycles around handcrafted, oversized aluminum frames that were both lighter and more flex-resistant than the steel models that dominated the industry at the time. We quickly followed up this success with a road racing model and a mountain bike model in 1984. Our creative reputation encouraged both bike dealers and customers to join the revolution, and widespread industry skepticism quickly gave way to a host of imitators.

        </p>
        <p>
			In 1997, Cannondale was the first company to feature large, oversized aluminum bike frames on cycling's biggest stage, the Tour de France. After powering his Cannondale to four stage victories at the 1999 Tour, the flamboyant Saeco team leader proclaimed "Cannondale is the best bike."

        </p>
        <p>
			With a reputation for shaking up the industry, we continued to push the entire cycling community with the release of our first carbon/aluminum frame, the Six13, flaunting the low weight with prison striped jerseys that read: Legalize My Cannondale.

        </p>
    </div>

</section>

bicicletas/app/views/page/home.html.erb
<div id="wrapper">
 <div class="slider-wrapper theme-default">
  <div class="ribbon"></div>
  <div id="slider" class="ramblingSlider">
	   <%= image_tag "comparativo-bianchi-solobici.jpg" %>
	   <%= image_tag "Coluer2baja.jpg" %>
	   <%= image_tag "images.jpeg" %>
	   <%= image_tag "Mondraker1baja.jpg" %>
	   <%= image_tag "pag29.jpg" %>
	   <%= image_tag "20111020193234_0.jpg" %>
	   <%= image_tag "Andreu_Lacondeguy_con_Mondraker_1_foto2_.jpg" %>
	   <%= image_tag "andreu lacondeguy_content.jpg" %>
  </div>
 </div>
</div>

<script>
  $(window).load(function(){
    $('#slider').ramblingSlider();
  });
</script>